<?php

/**
 * BaseAlbum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $album_nm
 * @property integer $artist_id
 * @property date $release_dt
 * @property Artist $Artist
 * @property Doctrine_Collection $album_id
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getAlbumNm()    Returns the current record's "album_nm" value
 * @method integer             getArtistId()   Returns the current record's "artist_id" value
 * @method date                getReleaseDt()  Returns the current record's "release_dt" value
 * @method Artist              getArtist()     Returns the current record's "Artist" value
 * @method Doctrine_Collection getAlbumId()    Returns the current record's "album_id" collection
 * @method Album               setId()         Sets the current record's "id" value
 * @method Album               setAlbumNm()    Sets the current record's "album_nm" value
 * @method Album               setArtistId()   Sets the current record's "artist_id" value
 * @method Album               setReleaseDt()  Sets the current record's "release_dt" value
 * @method Album               setArtist()     Sets the current record's "Artist" value
 * @method Album               setAlbumId()    Sets the current record's "album_id" collection
 * 
 * @package    musicapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlbum extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('album_tb');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('album_nm', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('artist_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('release_dt', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Artist', array(
             'local' => 'artist_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Song as album_id', array(
             'local' => 'id',
             'foreign' => 'album_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}