<?php

/**
 * BaseArtist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $artist_nm
 * @property string $real_nm
 * @property date $dob
 * @property integer $country_id
 * @property Country $Country
 * @property Doctrine_Collection $artist_id
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getArtistNm()   Returns the current record's "artist_nm" value
 * @method string              getRealNm()     Returns the current record's "real_nm" value
 * @method date                getDob()        Returns the current record's "dob" value
 * @method integer             getCountryId()  Returns the current record's "country_id" value
 * @method Country             getCountry()    Returns the current record's "Country" value
 * @method Doctrine_Collection getArtistId()   Returns the current record's "artist_id" collection
 * @method Artist              setId()         Sets the current record's "id" value
 * @method Artist              setArtistNm()   Sets the current record's "artist_nm" value
 * @method Artist              setRealNm()     Sets the current record's "real_nm" value
 * @method Artist              setDob()        Sets the current record's "dob" value
 * @method Artist              setCountryId()  Sets the current record's "country_id" value
 * @method Artist              setCountry()    Sets the current record's "Country" value
 * @method Artist              setArtistId()   Sets the current record's "artist_id" collection
 * 
 * @package    musicapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArtist extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('artist_tb');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('artist_nm', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('real_nm', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('dob', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('country_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Country', array(
             'local' => 'country_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Album as artist_id', array(
             'local' => 'id',
             'foreign' => 'artist_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}