<?php

/**
 * BaseCountry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $country_nm
 * @property Doctrine_Collection $country_id
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getCountryNm()  Returns the current record's "country_nm" value
 * @method Doctrine_Collection getCountryId()  Returns the current record's "country_id" collection
 * @method Country             setId()         Sets the current record's "id" value
 * @method Country             setCountryNm()  Sets the current record's "country_nm" value
 * @method Country             setCountryId()  Sets the current record's "country_id" collection
 * 
 * @package    musicapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCountry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('country_tb');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('country_nm', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Artist as country_id', array(
             'local' => 'id',
             'foreign' => 'country_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}