<?php

/**
 * BasePlaylist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $playlist_id
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method Doctrine_Collection getPlaylistId()  Returns the current record's "playlist_id" collection
 * @method Playlist            setId()          Sets the current record's "id" value
 * @method Playlist            setName()        Sets the current record's "name" value
 * @method Playlist            setPlaylistId()  Sets the current record's "playlist_id" collection
 * 
 * @package    musicapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlaylist extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('playlist_tb');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PlaylistSong as playlist_id', array(
             'local' => 'id',
             'foreign' => 'playlist_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}