<?php

/**
 * BaseStory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $story
 * @property integer $artist_id
 * @property Artist $Artist
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method string  getTitle()     Returns the current record's "title" value
 * @method string  getStory()     Returns the current record's "story" value
 * @method integer getArtistId()  Returns the current record's "artist_id" value
 * @method Artist  getArtist()    Returns the current record's "Artist" value
 * @method Story   setId()        Sets the current record's "id" value
 * @method Story   setTitle()     Sets the current record's "title" value
 * @method Story   setStory()     Sets the current record's "story" value
 * @method Story   setArtistId()  Sets the current record's "artist_id" value
 * @method Story   setArtist()    Sets the current record's "Artist" value
 * 
 * @package    musicapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('story_tb');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('story', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('artist_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Artist', array(
             'local' => 'artist_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}