<?php
// auto-generated by sfViewConfigHandler
// date: 2013/08/30 06:25:30
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('grid.css', '', array ());
  $response->addStylesheet('ie.css', '', array ());
  $response->addStylesheet('prettyPhoto.css', '', array ());
  $response->addStylesheet('reset.css', '', array ());
  $response->addStylesheet('style.css', '', array ());
  $response->addStylesheet('/pmSuperfishMenuPlugin/css/superfish.css', '', array ());
  $response->addJavascript('jquery-1.4.2.min.js', '', array ());
  $response->addJavascript('/pmSuperfishMenuPlugin/js/hoverIntent.js', '', array ());
  $response->addJavascript('/pmSuperfishMenuPlugin/js/superfish.js', '', array ());
  $response->addJavascript('cufon-replace.js', '', array ());
  $response->addJavascript('loadwindow.js', '', array ());
  $response->addJavascript('cufon-yui.js', '', array ());
  $response->addJavascript('easyTooltip', '', array ());
  $response->addJavascript('FF-cash', '', array ());
  $response->addJavascript('hover-image', '', array ());
  $response->addJavascript('html5', '', array ());
  $response->addJavascript('jquery.easing.1.3', '', array ());
  $response->addJavascript('jquery.galleriffic', '', array ());
  $response->addJavascript('jquery.opacityrollover', '', array ());
  $response->addJavascript('jquery.prettyPhoto', '', array ());
  $response->addJavascript('jquery-1.6.3.min', '', array ());
  $response->addJavascript('script', '', array ());
  $response->addJavascript('tms_presets', '', array ());
  $response->addJavascript('tms-0.3', '', array ());
  $response->addJavascript('Vegur_400.font', '', array ());
  $response->addJavascript('Vegur_700.font', '', array ());


