<?php

/**
 * AlbumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlbumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlbumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Album');
    }
    
    public function countAlbum(Doctrine_Query $q = null)
    {
        return $this->addActiveAlbumQuery($q)->count();
    }
    
   
    
    
     public function exeAlbum(Doctrine_Query $q = null)
    {
        return $this->addActiveAlbumQuery($q)->execute();
    }
    
    public function addActiveAlbumQuery(Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
        $q = Doctrine_Query::create()
        ->from('Album a');
        }
        
        
        return $q;
    }

}