<?php

/**
 * Artist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    musicapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Artist extends BaseArtist
{
   
    
    
        public function __toString()
    {
        return $this->getArtistNm();
    }
    
    
      public  function getAlbumCount()
    {
        
        $q = Doctrine_Query::create()
        ->from('Album a')
        ->where('artist_id = ?', $this->getId());

       // return Doctrine_Core::getTable('Album')->countAlbum($q);
        $rowid= -1;
        $root = new pmSuperfishMenu();
        $root->setRoot();
        $menu = new pmSuperfishMenu();
        $menu->setName(Doctrine_Core::getTable('Album')->countAlbum($q));
        $ii = 0;
        $i =Doctrine_Core::getTable('Album')->exeAlbum($q);
       foreach($i AS $row) {
            $rowid = $row['id'];
            $menu_item = new pmSuperfishMenuItem();       
            $menu_item->setName($row['album_nm'].'-'.$row['release_dt'])->setUrl("song/index?id=".$row['id']);
            $menu->addChild($row['album_nm']."_list", $menu_item);
            
             if ($ii == 0)
           {
            $root->addChild($row['album_nm']."_list", $menu) ;
           }
           
            $ii=$ii + 1; 
      }
      
      if($rowid == -1)
      {
          $menu_item = new pmSuperfishMenuItem();       
            $menu_item->setName("No Records Found")->setUrl("album/index");
            $menu->addChild("norecord_list", $menu_item);
          $root->addChild("norecord_list", $menu) ;
      }
      return $root; 
    }
    
     public  function getStoryCount()
    {
        $q = Doctrine_Query::create()
        ->from('Story s')
        ->where('artist_id = ?', $this->getId());

        return Doctrine_Core::getTable('Story')->countStory($q);
      
    }
    
   


    

}