<?php

/**
 * PlaylistSongTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlaylistSongTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlaylistSongTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlaylistSong');
    }
}