<?php

/**
 * Song
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    musicapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Song extends BaseSong
{

    
       public function __toString()
    {
        return $this->getSongNm();
    }

    
      public  function getFeatureCount()
    {
        
        $q = Doctrine_Query::create()
        ->from('Features a')
        ->where('song_id = ?', $this->getId())
                 ;

       // return Doctrine_Core::getTable('Album')->countAlbum($q);
        $rowid= -1;
        $root = new pmSuperfishMenu();
        $root->setRoot();
        $menu = new pmSuperfishMenu();
        $menu->setName(Doctrine_Core::getTable('Features')->countFeatures($q));
        $ii = 0;
        $i =Doctrine_Core::getTable('Features')->exeFeatures($q);
       foreach($i AS $row) {
            $rowid = $row['id'];
            $menu_item = new pmSuperfishMenuItem();   
            
            $aa = Doctrine_Query::create()
        ->from('Artist a')
        ->where('id = ?', $row['artist_id']);
            
           $a =Doctrine_Core::getTable('Artist')->exeArtist($aa);
          
           foreach($a AS $rower) {
            $menu_item->setName($rower['artist_nm'])->setUrl("artist/index?id=".$rower['id']);
            $menu->addChild($rower['artist_nm']."_list", $menu_item);
            
             if ($ii == 0)
           {
            $root->addChild($rower['artist_nm']."_list", $menu) ;
           }
           
           }
           
            $ii=$ii + 1; 
      }
      
      if($rowid == -1)
      {
          $menu_item = new pmSuperfishMenuItem();       
            $menu_item->setName("No Records Found")->setUrl("song/index");
            $menu->addChild("norecord_list", $menu_item);
          $root->addChild("norecord_list", $menu) ;
      }
      return $root; 
    }
    
    
}